name: Deploy to AWS S3

on:
  push:
    branches: [ "production"]

jobs:
  web-build:
    name: Web Dev Build
    runs-on: ubuntu-latest
    steps:
      - name: Show self-machine information
        run: uname -a
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo from production branch
        uses: actions/checkout@v3
        with:
          ref: production
      - name: Install npm dependency
        run: npm install
      - name: Build expo
        run: npx expo export -p web
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
          aws-bucket: s3://oldwesttracker
      - name: Deploy to S3
        run: |
          aws s3 sync ./WEB_deploy s3://oldwesttracker
